######################################################################
# Automatically generated by qmake (3.0) Tue Sep 18 17:42:20 2018
######################################################################

TEMPLATE = app
TARGET = myqt1
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
